-- Generated DDL for missing Fresha tables in voi_warehouse
-- Existing tables from your screenshot are intentionally excluded
-- Stage tables: no partition/clustering
-- Final tables: partition only when suitable, cluster by high-selectivity keys

-- CASH_FLOW
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.cash_flow_stage` (
  `TRANSACTION_REF` INT64,
  `SALE_ID` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `PROCESSED_BY_TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `PAYMENT_DATE` TIMESTAMP,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `CLIENT` STRING,
  `PROCESSED_BY_TEAM_MEMBER` STRING,
  `PAYER_DETAILS` STRING,
  `RECIPIENT_DETAILS` STRING,
  `TRANSACTION_TYPE` STRING,
  `APPOINTMENT_REF` STRING,
  `OPENING_BALANCE` NUMERIC,
  `AMOUNT` NUMERIC,
  `CLOSING_BALANCE` NUMERIC,
  `CURRENCY` STRING
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.cash_flow` (
  `TRANSACTION_REF` INT64,
  `SALE_ID` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `PROCESSED_BY_TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `PAYMENT_DATE` TIMESTAMP,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `CLIENT` STRING,
  `PROCESSED_BY_TEAM_MEMBER` STRING,
  `PAYER_DETAILS` STRING,
  `RECIPIENT_DETAILS` STRING,
  `TRANSACTION_TYPE` STRING,
  `APPOINTMENT_REF` STRING,
  `OPENING_BALANCE` NUMERIC,
  `AMOUNT` NUMERIC,
  `CLOSING_BALANCE` NUMERIC,
  `CURRENCY` STRING,
  `_loaded_at` TIMESTAMP
)
PARTITION BY DATE(`PAYMENT_DATE`)
CLUSTER BY `TRANSACTION_REF`, `LOCATION_ID`, `TEAM_MEMBER_ID`, `CLIENT_ID`
;

-- CLIENT_NOTES
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.client_notes_stage` (
  `NOTE_ID` INT64,
  `CLIENT_ID` INT64,
  `CREATED_BY_TEAM_MEMBER_ID` INT64,
  `LAST_EDITED_BY_TEAM_MEMBER_ID` INT64,
  `BODY` STRING,
  `CREATED_AT` TIMESTAMP,
  `LAST_EDITED_AT` TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.client_notes` (
  `NOTE_ID` INT64,
  `CLIENT_ID` INT64,
  `CREATED_BY_TEAM_MEMBER_ID` INT64,
  `LAST_EDITED_BY_TEAM_MEMBER_ID` INT64,
  `BODY` STRING,
  `CREATED_AT` TIMESTAMP,
  `LAST_EDITED_AT` TIMESTAMP,
  `_loaded_at` TIMESTAMP
)
PARTITION BY DATE(`LAST_EDITED_AT`)
CLUSTER BY `NOTE_ID`, `CLIENT_ID`, `CREATED_BY_TEAM_MEMBER_ID`, `LAST_EDITED_BY_TEAM_MEMBER_ID`
;

-- GIFT_CARDS
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.gift_cards_stage` (
  `GIFT_CARD_ID` NUMERIC,
  `SALE_ID` INT64,
  `SALE_ITEM_ID` INT64,
  `SALE_NUMBER` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `ISSUE_DATE` DATE,
  `EXPIRY_DATE` DATE,
  `REDEMPTION_DATE` TIMESTAMP,
  `CODE` STRING,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `PURCHASED_BY` STRING,
  `STATUS` STRING,
  `ISSUED_VALUE` NUMERIC,
  `TOTAL_SALES` NUMERIC,
  `DISCOUNT_VALUE` NUMERIC,
  `EXPIRED_VALUE` NUMERIC,
  `BALANCE` NUMERIC,
  `REDEEMED_VALUE` NUMERIC
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.gift_cards` (
  `GIFT_CARD_ID` NUMERIC,
  `SALE_ID` INT64,
  `SALE_ITEM_ID` INT64,
  `SALE_NUMBER` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `ISSUE_DATE` DATE,
  `EXPIRY_DATE` DATE,
  `REDEMPTION_DATE` TIMESTAMP,
  `CODE` STRING,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `PURCHASED_BY` STRING,
  `STATUS` STRING,
  `ISSUED_VALUE` NUMERIC,
  `TOTAL_SALES` NUMERIC,
  `DISCOUNT_VALUE` NUMERIC,
  `EXPIRED_VALUE` NUMERIC,
  `BALANCE` NUMERIC,
  `REDEEMED_VALUE` NUMERIC,
  `_loaded_at` TIMESTAMP
)
PARTITION BY `ISSUE_DATE`
CLUSTER BY `GIFT_CARD_ID`, `LOCATION_ID`, `TEAM_MEMBER_ID`, `CLIENT_ID`
;

-- LOCATIONS
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.locations_stage` (
  `LOCATION_ID` INT64,
  `NAME` STRING,
  `PHONE` STRING,
  `EMAIL` STRING,
  `DELETED_AT` TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.locations` (
  `LOCATION_ID` INT64,
  `NAME` STRING,
  `PHONE` STRING,
  `EMAIL` STRING,
  `DELETED_AT` TIMESTAMP,
  `_loaded_at` TIMESTAMP
)
CLUSTER BY `LOCATION_ID`
;

-- MEMBERSHIPS
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.memberships_stage` (
  `MEMBERSHIP_PK` STRING,
  `MEMBERSHIP_ID` INT64,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `START_DATE` DATE,
  `END_DATE` DATE,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `CLIENT` STRING,
  `MEMBERSHIP_TYPE` STRING,
  `MEMBERSHIP_NAME` STRING,
  `MEMBERSHIP_STATUS` STRING,
  `SERVICES_INCLUDED` INT64,
  `TOTAL_SESSIONS` INT64,
  `SALE_VALUE` NUMERIC
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.memberships` (
  `MEMBERSHIP_PK` STRING,
  `MEMBERSHIP_ID` INT64,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `START_DATE` DATE,
  `END_DATE` DATE,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `CLIENT` STRING,
  `MEMBERSHIP_TYPE` STRING,
  `MEMBERSHIP_NAME` STRING,
  `MEMBERSHIP_STATUS` STRING,
  `SERVICES_INCLUDED` INT64,
  `TOTAL_SESSIONS` INT64,
  `SALE_VALUE` NUMERIC,
  `_loaded_at` TIMESTAMP
)
PARTITION BY `START_DATE`
CLUSTER BY `MEMBERSHIP_PK`, `LOCATION_ID`, `TEAM_MEMBER_ID`, `CLIENT_ID`
;

-- OCCUPANCY
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.occupancy_stage` (
  `OCCUPANCY_EMPLOYEE_PK` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `DATE` DATE,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `SHIFT_MINUTES` NUMERIC,
  `TIME_OFF_MINUTES` INT64,
  `BLOCKED_MINUTES` INT64,
  `AVAILABLE_MINUTES` NUMERIC,
  `BOOKED_MINUTES` INT64,
  `UNBOOKED_MINUTES` NUMERIC,
  `OCCUPANCY_RATE` NUMERIC
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.occupancy` (
  `OCCUPANCY_EMPLOYEE_PK` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `DATE` DATE,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `SHIFT_MINUTES` NUMERIC,
  `TIME_OFF_MINUTES` INT64,
  `BLOCKED_MINUTES` INT64,
  `AVAILABLE_MINUTES` NUMERIC,
  `BOOKED_MINUTES` INT64,
  `UNBOOKED_MINUTES` NUMERIC,
  `OCCUPANCY_RATE` NUMERIC,
  `_loaded_at` TIMESTAMP
)
PARTITION BY `DATE`
CLUSTER BY `OCCUPANCY_EMPLOYEE_PK`, `LOCATION_ID`, `TEAM_MEMBER_ID`
;

-- PRODUCTS
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.products_stage` (
  `PRODUCT_ID` INT64,
  `SUPPLIER_NAME` STRING,
  `BRAND_NAME` STRING,
  `PRODUCT_NAME` STRING,
  `CATEGORY_NAME` STRING,
  `SKU` STRING,
  `BARCODE` STRING,
  `HAS_DESCRIPTION` BOOL,
  `HAS_IMAGE` BOOL,
  `HAS_UNLIMITED_STOCK` BOOL,
  `UNITS` NUMERIC,
  `UNIT_OF_MEASURE` STRING,
  `COST_PRICE` NUMERIC,
  `RETAIL_PRICE` NUMERIC
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.products` (
  `PRODUCT_ID` INT64,
  `SUPPLIER_NAME` STRING,
  `BRAND_NAME` STRING,
  `PRODUCT_NAME` STRING,
  `CATEGORY_NAME` STRING,
  `SKU` STRING,
  `BARCODE` STRING,
  `HAS_DESCRIPTION` BOOL,
  `HAS_IMAGE` BOOL,
  `HAS_UNLIMITED_STOCK` BOOL,
  `UNITS` NUMERIC,
  `UNIT_OF_MEASURE` STRING,
  `COST_PRICE` NUMERIC,
  `RETAIL_PRICE` NUMERIC,
  `_loaded_at` TIMESTAMP
)
CLUSTER BY `PRODUCT_ID`
;

-- SCHEDULED_SHIFTS
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.scheduled_shifts_stage` (
  `SHIFT_ID` STRING,
  `CALENDAR_DATE` DATE,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `TEAM_MEMBER` STRING,
  `LOCATION` STRING,
  `SCHEDULED_START_TIMESTAMP` TIMESTAMP,
  `SCHEDULED_END_TIMESTAMP` TIMESTAMP,
  `MINUTES_SCHEDULED` NUMERIC,
  `HOURS_SCHEDULED` NUMERIC
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.scheduled_shifts` (
  `SHIFT_ID` STRING,
  `CALENDAR_DATE` DATE,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `TEAM_MEMBER` STRING,
  `LOCATION` STRING,
  `SCHEDULED_START_TIMESTAMP` TIMESTAMP,
  `SCHEDULED_END_TIMESTAMP` TIMESTAMP,
  `MINUTES_SCHEDULED` NUMERIC,
  `HOURS_SCHEDULED` NUMERIC,
  `_loaded_at` TIMESTAMP
)
PARTITION BY `CALENDAR_DATE`
CLUSTER BY `SHIFT_ID`, `LOCATION_ID`, `TEAM_MEMBER_ID`
;

-- SERVICES
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.services_stage` (
  `SERVICE_ID` INT64,
  `NAME` STRING,
  `DESCRIPTION` STRING,
  `DELETED_AT` TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.services` (
  `SERVICE_ID` INT64,
  `NAME` STRING,
  `DESCRIPTION` STRING,
  `DELETED_AT` TIMESTAMP,
  `_loaded_at` TIMESTAMP
)
CLUSTER BY `SERVICE_ID`
;

-- SERVICE_CHARGES
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.service_charges_stage` (
  `SERVICE_CHARGE_ID` INT64,
  `SALE_ID` INT64,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `SERVICE_CHARGE_DATE` DATE,
  `SERVICE_CHARGE` STRING,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `CLIENT` STRING,
  `SERVICE_CHARGE_FLAT_RATE` NUMERIC,
  `SERVICE_CHARGE_PERCENTAGE_RATE` NUMERIC,
  `NET_AMOUNT` NUMERIC,
  `TAX` NUMERIC,
  `TOTAL_AMOUNT` NUMERIC,
  `CURRENCY_CODE` STRING
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.service_charges` (
  `SERVICE_CHARGE_ID` INT64,
  `SALE_ID` INT64,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `SERVICE_CHARGE_DATE` DATE,
  `SERVICE_CHARGE` STRING,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `CLIENT` STRING,
  `SERVICE_CHARGE_FLAT_RATE` NUMERIC,
  `SERVICE_CHARGE_PERCENTAGE_RATE` NUMERIC,
  `NET_AMOUNT` NUMERIC,
  `TAX` NUMERIC,
  `TOTAL_AMOUNT` NUMERIC,
  `CURRENCY_CODE` STRING,
  `_loaded_at` TIMESTAMP
)
PARTITION BY `SERVICE_CHARGE_DATE`
CLUSTER BY `SERVICE_CHARGE_ID`, `LOCATION_ID`, `TEAM_MEMBER_ID`, `CLIENT_ID`
;

-- STOCK_MOVEMENTS
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.stock_movements_stage` (
  `STOCK_MOVEMENT_ID` INT64,
  `LOCATION_ID` INT64,
  `SALE_ID` INT64,
  `SALE_DATE` TIMESTAMP,
  `LOCATION` STRING,
  `SUPPLIER` STRING,
  `BRAND` STRING,
  `CATEGORY` STRING,
  `PRODUCT` STRING,
  `PRIMARY_SKU` STRING,
  `BARCODE` STRING,
  `IS_UNLIMITED` BOOL,
  `ADJUSTMENT_REASON` STRING,
  `ADJUSTMENT_REF` STRING,
  `QUANTITY` INT64,
  `UNIT_COST` NUMERIC,
  `COST` NUMERIC,
  `RETAIL_PRICE` NUMERIC
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.stock_movements` (
  `STOCK_MOVEMENT_ID` INT64,
  `LOCATION_ID` INT64,
  `SALE_ID` INT64,
  `SALE_DATE` TIMESTAMP,
  `LOCATION` STRING,
  `SUPPLIER` STRING,
  `BRAND` STRING,
  `CATEGORY` STRING,
  `PRODUCT` STRING,
  `PRIMARY_SKU` STRING,
  `BARCODE` STRING,
  `IS_UNLIMITED` BOOL,
  `ADJUSTMENT_REASON` STRING,
  `ADJUSTMENT_REF` STRING,
  `QUANTITY` INT64,
  `UNIT_COST` NUMERIC,
  `COST` NUMERIC,
  `RETAIL_PRICE` NUMERIC,
  `_loaded_at` TIMESTAMP
)
PARTITION BY DATE(`SALE_DATE`)
CLUSTER BY `STOCK_MOVEMENT_ID`, `LOCATION_ID`, `SALE_ID`, `ADJUSTMENT_REF`
;

-- STOCK_ORDERS
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.stock_orders_stage` (
  `ORDER_ITEM_ID` INT64,
  `ORDER_ID` INT64,
  `LOCATION_ID` INT64,
  `ORDERED_BY_TEAM_MEMBER_ID` INT64,
  `PRODUCT_ID` INT64,
  `ORDERED_AT` TIMESTAMP,
  `EXPECTED_AT` DATE,
  `RECEIVED_AT` TIMESTAMP,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `SUPPLIER_NAME` STRING,
  `BRAND_NAME` STRING,
  `PRODUCT_NAME` STRING,
  `CATEGORY_NAME` STRING,
  `REFERENCE_NUMBER` STRING,
  `ORDER_STATUS` STRING,
  `ORDERED_QUANTITY` INT64,
  `RECEIVED_QUANTITY` INT64,
  `CANCELLED_QUANTITY` INT64,
  `PENDING_QUANTITY` INT64,
  `AVERAGE_UNIT_COST` NUMERIC,
  `TOTAL_COST` NUMERIC
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.stock_orders` (
  `ORDER_ITEM_ID` INT64,
  `ORDER_ID` INT64,
  `LOCATION_ID` INT64,
  `ORDERED_BY_TEAM_MEMBER_ID` INT64,
  `PRODUCT_ID` INT64,
  `ORDERED_AT` TIMESTAMP,
  `EXPECTED_AT` DATE,
  `RECEIVED_AT` TIMESTAMP,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `SUPPLIER_NAME` STRING,
  `BRAND_NAME` STRING,
  `PRODUCT_NAME` STRING,
  `CATEGORY_NAME` STRING,
  `REFERENCE_NUMBER` STRING,
  `ORDER_STATUS` STRING,
  `ORDERED_QUANTITY` INT64,
  `RECEIVED_QUANTITY` INT64,
  `CANCELLED_QUANTITY` INT64,
  `PENDING_QUANTITY` INT64,
  `AVERAGE_UNIT_COST` NUMERIC,
  `TOTAL_COST` NUMERIC,
  `_loaded_at` TIMESTAMP
)
PARTITION BY DATE(`ORDERED_AT`)
CLUSTER BY `ORDER_ITEM_ID`, `LOCATION_ID`, `PRODUCT_ID`, `ORDER_ID`
;

-- TAXES
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.taxes_stage` (
  `SALE_ITEM_TAX_ID` INT64,
  `SALE_ID` INT64,
  `SALE_ITEM_ID` INT64,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `SALE_DATE` TIMESTAMP,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `CLIENT` STRING,
  `APPOINTMENT_CHANNEL` STRING,
  `APPOINTMENT_REF` STRING,
  `SALE_NUMBER` STRING,
  `SALE_STATUS` STRING,
  `TRANSACTION_TYPE` STRING,
  `PAYMENT_METHOD` STRING,
  `SALE_TYPE` STRING,
  `SUPPLIER` STRING,
  `BRAND` STRING,
  `CATEGORY` STRING,
  `ITEM` STRING,
  `SKU` STRING,
  `BARCODE` STRING,
  `TAX_NAME` STRING,
  `CURRENCY_CODE` STRING,
  `COST` NUMERIC,
  `NET_SALES` NUMERIC,
  `TAX_RATE` NUMERIC,
  `ITEMS_SOLD` INT64,
  `TAX_ON_NET_SALES` NUMERIC
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.taxes` (
  `SALE_ITEM_TAX_ID` INT64,
  `SALE_ID` INT64,
  `SALE_ITEM_ID` INT64,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `SALE_DATE` TIMESTAMP,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `CLIENT` STRING,
  `APPOINTMENT_CHANNEL` STRING,
  `APPOINTMENT_REF` STRING,
  `SALE_NUMBER` STRING,
  `SALE_STATUS` STRING,
  `TRANSACTION_TYPE` STRING,
  `PAYMENT_METHOD` STRING,
  `SALE_TYPE` STRING,
  `SUPPLIER` STRING,
  `BRAND` STRING,
  `CATEGORY` STRING,
  `ITEM` STRING,
  `SKU` STRING,
  `BARCODE` STRING,
  `TAX_NAME` STRING,
  `CURRENCY_CODE` STRING,
  `COST` NUMERIC,
  `NET_SALES` NUMERIC,
  `TAX_RATE` NUMERIC,
  `ITEMS_SOLD` INT64,
  `TAX_ON_NET_SALES` NUMERIC,
  `_loaded_at` TIMESTAMP
)
PARTITION BY DATE(`SALE_DATE`)
CLUSTER BY `SALE_ITEM_TAX_ID`, `LOCATION_ID`, `TEAM_MEMBER_ID`, `CLIENT_ID`
;

-- TIMESHEETS
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.timesheets_stage` (
  `TIMESHEET_ID` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `EXPECTED_START` TIMESTAMP,
  `ACTUAL_START` TIMESTAMP,
  `EXPECTED_END` TIMESTAMP,
  `ACTUAL_END` TIMESTAMP,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `SOURCE` STRING,
  `CLOCK_IN` TIME,
  `CLOCK_IN_TYPE` STRING,
  `CLOCK_IN_DEVIATION` STRING,
  `CLOCK_OUT` TIME,
  `CLOCK_OUT_TYPE` STRING,
  `CLOCK_OUT_DEVIATION` STRING,
  `PAID_BREAK_HOURS` NUMERIC,
  `PAID_BREAK_MINUTES` INT64,
  `UNPAID_BREAK_HOURS` NUMERIC,
  `UNPAID_BREAK_MINUTES` INT64,
  `HOURS_WORKED` NUMERIC,
  `HOURS_SCHEDULED` NUMERIC,
  `HOURS_TOTAL_PAID` NUMERIC
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.timesheets` (
  `TIMESHEET_ID` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `EXPECTED_START` TIMESTAMP,
  `ACTUAL_START` TIMESTAMP,
  `EXPECTED_END` TIMESTAMP,
  `ACTUAL_END` TIMESTAMP,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `SOURCE` STRING,
  `CLOCK_IN` TIME,
  `CLOCK_IN_TYPE` STRING,
  `CLOCK_IN_DEVIATION` STRING,
  `CLOCK_OUT` TIME,
  `CLOCK_OUT_TYPE` STRING,
  `CLOCK_OUT_DEVIATION` STRING,
  `PAID_BREAK_HOURS` NUMERIC,
  `PAID_BREAK_MINUTES` INT64,
  `UNPAID_BREAK_HOURS` NUMERIC,
  `UNPAID_BREAK_MINUTES` INT64,
  `HOURS_WORKED` NUMERIC,
  `HOURS_SCHEDULED` NUMERIC,
  `HOURS_TOTAL_PAID` NUMERIC,
  `_loaded_at` TIMESTAMP
)
PARTITION BY DATE(`EXPECTED_START`)
CLUSTER BY `TIMESHEET_ID`, `LOCATION_ID`, `TEAM_MEMBER_ID`
;

-- TIME_OFF
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.time_off_stage` (
  `TIME_OFF_PK` STRING,
  `TIME_OFF_ID` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `START_DATE` DATE,
  `START_TIME` TIME,
  `END_DATE` DATE,
  `END_TIME` TIME,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `TIME_OFF_TYPE` STRING,
  `STATUS` STRING,
  `DURATION_MINUTES` INT64,
  `DURATION_HOURS` STRING
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.time_off` (
  `TIME_OFF_PK` STRING,
  `TIME_OFF_ID` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `START_DATE` DATE,
  `START_TIME` TIME,
  `END_DATE` DATE,
  `END_TIME` TIME,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `TIME_OFF_TYPE` STRING,
  `STATUS` STRING,
  `DURATION_MINUTES` INT64,
  `DURATION_HOURS` STRING,
  `_loaded_at` TIMESTAMP
)
PARTITION BY `START_DATE`
CLUSTER BY `TIME_OFF_PK`, `LOCATION_ID`, `TEAM_MEMBER_ID`, `TIME_OFF_ID`
;

-- TIPS
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.tips_stage` (
  `TIP_ID` INT64,
  `SALE_ID` INT64,
  `SALE_NUMBER` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `TIP_DATE` DATE,
  `TEAM_MEMBER` STRING,
  `CLIENT` STRING,
  `CLIENT_GENDER` STRING,
  `LOCATION` STRING,
  `TRANSACTION_TYPE` STRING,
  `TIP_CHANNEL` STRING,
  `PAYMENT_METHOD` STRING,
  `TIPS_COLLECTED` NUMERIC,
  `TIPS_REFUNDED` NUMERIC,
  `CLIENT_RETENTION_SOURCE` STRING,
  `CURRENCY_CODE` STRING
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.tips` (
  `TIP_ID` INT64,
  `SALE_ID` INT64,
  `SALE_NUMBER` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `CLIENT_ID` INT64,
  `TIP_DATE` DATE,
  `TEAM_MEMBER` STRING,
  `CLIENT` STRING,
  `CLIENT_GENDER` STRING,
  `LOCATION` STRING,
  `TRANSACTION_TYPE` STRING,
  `TIP_CHANNEL` STRING,
  `PAYMENT_METHOD` STRING,
  `TIPS_COLLECTED` NUMERIC,
  `TIPS_REFUNDED` NUMERIC,
  `CLIENT_RETENTION_SOURCE` STRING,
  `CURRENCY_CODE` STRING,
  `_loaded_at` TIMESTAMP
)
PARTITION BY `TIP_DATE`
CLUSTER BY `TIP_ID`, `LOCATION_ID`, `TEAM_MEMBER_ID`, `CLIENT_ID`
;

-- WAGES
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.wages_stage` (
  `WAGE_PK` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `WAGE_DATE` DATE,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `PAID_BREAKS` NUMERIC,
  `UNPAID_BREAKS` NUMERIC,
  `REGULAR_PAID_HOURS` NUMERIC,
  `OVERTIME_PAID_HOURS` NUMERIC,
  `REGULAR_WAGE_AMOUNT` NUMERIC,
  `OVERTIME_WAGE_AMOUNT` NUMERIC,
  `HOURS_WORKED` NUMERIC,
  `TOTAL_PAID_HOURS` NUMERIC,
  `TOTAL_WAGES` NUMERIC
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.wages` (
  `WAGE_PK` STRING,
  `LOCATION_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `WAGE_DATE` DATE,
  `LOCATION` STRING,
  `TEAM_MEMBER` STRING,
  `PAID_BREAKS` NUMERIC,
  `UNPAID_BREAKS` NUMERIC,
  `REGULAR_PAID_HOURS` NUMERIC,
  `OVERTIME_PAID_HOURS` NUMERIC,
  `REGULAR_WAGE_AMOUNT` NUMERIC,
  `OVERTIME_WAGE_AMOUNT` NUMERIC,
  `HOURS_WORKED` NUMERIC,
  `TOTAL_PAID_HOURS` NUMERIC,
  `TOTAL_WAGES` NUMERIC,
  `_loaded_at` TIMESTAMP
)
PARTITION BY `WAGE_DATE`
CLUSTER BY `WAGE_PK`, `LOCATION_ID`, `TEAM_MEMBER_ID`
;

-- WAITLIST
CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.waitlist_stage` (
  `WAITLIST_PK` STRING,
  `WAITLIST_REF` STRING,
  `LOCATION_ID` INT64,
  `APPOINTMENT_ID` INT64,
  `CLIENT_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `SERVICE_ID` INT64,
  `CREATED_BY_TEAM_MEMBER_ID` INT64,
  `DELETED_BY_TEAM_MEMBER_ID` INT64,
  `FROM_DATE` DATE,
  `FROM_TIME` TIME,
  `TO_DATE` DATE,
  `TO_TIME` TIME,
  `CREATED_DATE` TIMESTAMP,
  `DELETED_DATE` TIMESTAMP,
  `LOCATION` STRING,
  `CLIENT` STRING,
  `CLIENT_PHONE_NUMBER` STRING,
  `IS_NEW_CLIENT` BOOL,
  `TEAM_MEMBER` STRING,
  `SERVICE_NAME` STRING,
  `CATEGORY_NAME` STRING,
  `WAITLIST_STATUS` STRING,
  `APPOINTMENT_CHANNEL` STRING,
  `APPOINTMENT_REF` STRING,
  `NOTE` STRING,
  `SKU` STRING,
  `CREATED_BY_TEAM_MEMBER` STRING,
  `DELETED_BY_TEAM_MEMBER` STRING,
  `SERVICE_DURATION` INT64,
  `SERVICE_PRICE` NUMERIC
);

CREATE TABLE IF NOT EXISTS `victims-of-ink-data-platform.voi_warehouse.waitlist` (
  `WAITLIST_PK` STRING,
  `WAITLIST_REF` STRING,
  `LOCATION_ID` INT64,
  `APPOINTMENT_ID` INT64,
  `CLIENT_ID` INT64,
  `TEAM_MEMBER_ID` INT64,
  `SERVICE_ID` INT64,
  `CREATED_BY_TEAM_MEMBER_ID` INT64,
  `DELETED_BY_TEAM_MEMBER_ID` INT64,
  `FROM_DATE` DATE,
  `FROM_TIME` TIME,
  `TO_DATE` DATE,
  `TO_TIME` TIME,
  `CREATED_DATE` TIMESTAMP,
  `DELETED_DATE` TIMESTAMP,
  `LOCATION` STRING,
  `CLIENT` STRING,
  `CLIENT_PHONE_NUMBER` STRING,
  `IS_NEW_CLIENT` BOOL,
  `TEAM_MEMBER` STRING,
  `SERVICE_NAME` STRING,
  `CATEGORY_NAME` STRING,
  `WAITLIST_STATUS` STRING,
  `APPOINTMENT_CHANNEL` STRING,
  `APPOINTMENT_REF` STRING,
  `NOTE` STRING,
  `SKU` STRING,
  `CREATED_BY_TEAM_MEMBER` STRING,
  `DELETED_BY_TEAM_MEMBER` STRING,
  `SERVICE_DURATION` INT64,
  `SERVICE_PRICE` NUMERIC,
  `_loaded_at` TIMESTAMP
)
PARTITION BY DATE(`CREATED_DATE`)
CLUSTER BY `WAITLIST_PK`, `LOCATION_ID`, `TEAM_MEMBER_ID`, `CLIENT_ID`
;
