select
  lead_id,
  first_name,
  last_name,
  concat(ifnull(first_name, ''), ' ', ifnull(last_name, '')) as full_name,
  lower(trim(concat(ifnull(first_name, ''), ' ', ifnull(last_name, '')))) as full_name_norm,
  email,
  lower(trim(email)) as email_norm,
  mobile_number,
  regexp_replace(ifnull(mobile_number, ''), r'[^0-9]', '') as mobile_digits,
  lead_source,
  how_heard,
  preferred_artist,
  image_url,
  inquiry_message,
  gclid,
  fbclid,
  msclkid,
  utm_source,
  utm_medium,
  utm_campaign,
  utm_term,
  utm_content,
  landing_page_url,
  referrer_url,
  form_name,
  cast(consent_marketing as bool) as consent_marketing,
  status as lead_status,
  assigned_to,
  cast(created_at as timestamp) as created_at,
  cast(updated_at as timestamp) as updated_at,
  cast(_ingested_at as timestamp) as ingested_at
from {{ source('voi_ops', 'leads_inbox_raw') }}
