select
  cast(SALE_ITEM_ID as int64) as sale_item_id,
  cast(SALE_ID as int64) as sale_id,
  cast(TEAM_MEMBER_ID as int64) as team_member_id,
  TEAM_MEMBER as team_member,
  lower(trim(TEAM_MEMBER)) as team_member_norm,
  cast(CLIENT_ID as int64) as client_id,
  CLIENT as client,
  SALE_NUMBER as sale_number,
  SALE_TYPE as sale_type,
  CATEGORY as category,
  ITEM as item_name,
  SKU as sku,
  cast(QUANTITY as int64) as quantity,
  cast(GROSS_SALES as numeric) as gross_sales,
  cast(DISCOUNTS as numeric) as discounts,
  cast(NET_SALES as numeric) as net_sales,
  cast(TAXES_ON_NET_SALES as numeric) as taxes_on_net_sales,
  cast(TOTAL_SALES as numeric) as total_sales,
  CURRENCY_CODE as currency_code,
  cast(SALE_DATE as timestamp) as sale_ts_utc,
  date(SALE_DATE, "Australia/Melbourne") as sale_day_melbourne,
  date_trunc(date(SALE_DATE, "Australia/Melbourne"), week(saturday)) as pay_week_start
from {{ source('voi_warehouse', 'sale_items') }}
