select
  SALE_NUMBER as sale_number,
  cast(PAYMENT_NO as int64) as payment_no,
  APPOINTMENT_REF as appointment_ref,
  cast(SALE_ID as int64) as sale_id,
  cast(APPOINTMENT_ID as int64) as appointment_id,
  cast(LOCATION_ID as int64) as location_id,
  LOCATION as location,
  cast(TEAM_MEMBER_ID as int64) as team_member_id,
  TEAM_MEMBER as team_member,
  cast(CLIENT_ID as int64) as client_id,
  CLIENT as client,
  GIFT_CARD_CODE as gift_card_code,
  TRANSACTION_TYPE as transaction_type,
  cast(IS_DEPOSIT_REDEMPTION as bool) as is_deposit_redemption,
  cast(IS_GIFT_CARD_REDEMPTION as bool) as is_gift_card_redemption,
  PAYMENT_METHOD as payment_method,
  CURRENCY_CODE as currency_code,
  cast(AMOUNT as numeric) as amount,
  cast(REFUND_AMOUNT as numeric) as refund_amount,
  cast(PAYMENT_AMOUNT as numeric) as payment_amount,
  cast(CHANGE_AMOUNT as numeric) as change_amount,
  cast(PAYMENT_DATE as timestamp) as payment_ts_raw_utc,
  datetime(cast(PAYMENT_DATE as timestamp), {{ voi_tz() | tojson }}) as payment_datetime_local,
  -- PAYMENT_DATE is already stored as true UTC TIMESTAMP in warehouse.
  cast(PAYMENT_DATE as timestamp) as payment_ts_utc,
  date(cast(PAYMENT_DATE as timestamp), {{ voi_tz() | tojson }}) as payment_day_melbourne,
  date_trunc(date(cast(PAYMENT_DATE as timestamp), {{ voi_tz() | tojson }}), week(saturday)) as pay_week_start
from {{ source('voi_warehouse', 'payments') }}
