name: "voi_analytics"
version: "1.0.0"
config-version: 2

profile: "voi_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  voi_analytics:
    +materialized: view
    staging:
      +schema: voi_staging
    marts:
      +schema: voi_reporting
      +materialized: table
